#!/usr/bin/env python3
"""
Fix dependency issues by adding self-contained implementations and fallback mechanisms
"""

import json

def fix_dependency_issues():
    """Add self-contained implementations and fallback mechanisms"""
    
    # Read existing notebook
    with open('complete_neat_training.ipynb', 'r', encoding='utf-8') as f:
        notebook = json.load(f)
    
    # Find the library imports cell to add fallback implementations after it
    imports_cell_index = None
    for i, cell in enumerate(notebook['cells']):
        if "Library Imports" in ''.join(cell['source']):
            imports_cell_index = i
            break
    
    if imports_cell_index is None:
        print("❌ Library imports cell not found")
        return
    
    # Create self-contained implementations cell
    self_contained_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "self_contained_implementations"},
        "outputs": [],
        "source": [
            "# Self-Contained NEAT Implementations (Fallback for Missing Modules)\n",
            "import numpy as np\n",
            "import random\n",
            "from typing import Dict, List, Tuple, Optional, Any\n",
            "from enum import Enum\n",
            "import copy\n",
            "\n",
            "# NEAT Enums and Constants\n",
            "class NodeType(Enum):\n",
            "    INPUT = \"input\"\n",
            "    HIDDEN = \"hidden\"\n",
            "    OUTPUT = \"output\"\n",
            "\n",
            "class ActivationFunction(Enum):\n",
            "    LINEAR = \"linear\"\n",
            "    RELU = \"relu\"\n",
            "    TANH = \"tanh\"\n",
            "    SIGMOID = \"sigmoid\"\n",
            "    LEAKY_RELU = \"leaky_relu\"\n",
            "    ELU = \"elu\"\n",
            "    SWISH = \"swish\"\n",
            "\n",
            "# NEAT Node Implementation\n",
            "class NEATNode:\n",
            "    \"\"\"Self-contained NEAT node implementation\"\"\"\n",
            "    \n",
            "    def __init__(self, node_id: int, node_type: NodeType, activation: ActivationFunction = ActivationFunction.RELU):\n",
            "        self.node_id = node_id\n",
            "        self.node_type = node_type\n",
            "        self.activation = activation\n",
            "        self.bias = 0.0\n",
            "        self.value = 0.0\n",
            "    \n",
            "    def __str__(self):\n",
            "        return f\"Node({self.node_id}, {self.node_type.value}, {self.activation.value})\"\n",
            "\n",
            "# NEAT Connection Implementation\n",
            "class NEATConnection:\n",
            "    \"\"\"Self-contained NEAT connection implementation\"\"\"\n",
            "    \n",
            "    def __init__(self, innovation_number: int, input_node: int, output_node: int, weight: float = 1.0, enabled: bool = True):\n",
            "        self.innovation_number = innovation_number\n",
            "        self.input_node = input_node\n",
            "        self.output_node = output_node\n",
            "        self.weight = weight\n",
            "        self.enabled = enabled\n",
            "    \n",
            "    def __str__(self):\n",
            "        return f\"Connection({self.input_node}->{self.output_node}, w={self.weight:.3f}, enabled={self.enabled})\"\n",
            "\n",
            "# NEAT Genome Implementation\n",
            "class NEATGenome:\n",
            "    \"\"\"Self-contained NEAT genome implementation\"\"\"\n",
            "    \n",
            "    def __init__(self, input_size: int, output_size: int):\n",
            "        self.input_size = input_size\n",
            "        self.output_size = output_size\n",
            "        self.nodes = {}\n",
            "        self.connections = {}\n",
            "        self.fitness = 0.0\n",
            "        self.adjusted_fitness = 0.0\n",
            "        self.species_id = None\n",
            "        \n",
            "        # Initialize input nodes\n",
            "        for i in range(input_size):\n",
            "            self.nodes[i] = NEATNode(i, NodeType.INPUT, ActivationFunction.LINEAR)\n",
            "        \n",
            "        # Initialize output nodes\n",
            "        for i in range(output_size):\n",
            "            node_id = input_size + i\n",
            "            self.nodes[node_id] = NEATNode(node_id, NodeType.OUTPUT, ActivationFunction.SIGMOID)\n",
            "        \n",
            "        # Add initial connections (fully connected)\n",
            "        innovation = 0\n",
            "        for input_id in range(input_size):\n",
            "            for output_id in range(input_size, input_size + output_size):\n",
            "                self.connections[innovation] = NEATConnection(\n",
            "                    innovation, input_id, output_id, \n",
            "                    weight=random.uniform(-1.0, 1.0)\n",
            "                )\n",
            "                innovation += 1\n",
            "    \n",
            "    def add_node(self, connection_id: int) -> bool:\n",
            "        \"\"\"Add a new hidden node by splitting a connection\"\"\"\n",
            "        if connection_id not in self.connections:\n",
            "            return False\n",
            "        \n",
            "        conn = self.connections[connection_id]\n",
            "        if not conn.enabled:\n",
            "            return False\n",
            "        \n",
            "        # Create new hidden node\n",
            "        new_node_id = max(self.nodes.keys()) + 1\n",
            "        new_node = NEATNode(new_node_id, NodeType.HIDDEN, ActivationFunction.RELU)\n",
            "        self.nodes[new_node_id] = new_node\n",
            "        \n",
            "        # Disable original connection\n",
            "        conn.enabled = False\n",
            "        \n",
            "        # Add new connections\n",
            "        max_innovation = max(self.connections.keys()) if self.connections else -1\n",
            "        \n",
            "        # Input to new node\n",
            "        self.connections[max_innovation + 1] = NEATConnection(\n",
            "            max_innovation + 1, conn.input_node, new_node_id, weight=1.0\n",
            "        )\n",
            "        \n",
            "        # New node to output\n",
            "        self.connections[max_innovation + 2] = NEATConnection(\n",
            "            max_innovation + 2, new_node_id, conn.output_node, weight=conn.weight\n",
            "        )\n",
            "        \n",
            "        return True\n",
            "    \n",
            "    def add_connection(self, input_node: int, output_node: int) -> bool:\n",
            "        \"\"\"Add a new connection between nodes\"\"\"\n",
            "        # Check if connection already exists\n",
            "        for conn in self.connections.values():\n",
            "            if conn.input_node == input_node and conn.output_node == output_node:\n",
            "                return False\n",
            "        \n",
            "        # Check if it would create a cycle (simple check)\n",
            "        if input_node >= output_node:\n",
            "            return False\n",
            "        \n",
            "        # Add new connection\n",
            "        max_innovation = max(self.connections.keys()) if self.connections else -1\n",
            "        self.connections[max_innovation + 1] = NEATConnection(\n",
            "            max_innovation + 1, input_node, output_node, \n",
            "            weight=random.uniform(-1.0, 1.0)\n",
            "        )\n",
            "        \n",
            "        return True\n",
            "    \n",
            "    def mutate_weights(self, mutation_rate: float = 0.1, mutation_strength: float = 0.1):\n",
            "        \"\"\"Mutate connection weights\"\"\"\n",
            "        for conn in self.connections.values():\n",
            "            if random.random() < mutation_rate:\n",
            "                if random.random() < 0.1:  # 10% chance of weight replacement\n",
            "                    conn.weight = random.uniform(-1.0, 1.0)\n",
            "                else:  # 90% chance of weight perturbation\n",
            "                    conn.weight += random.gauss(0, mutation_strength)\n",
            "                    conn.weight = np.clip(conn.weight, -1.0, 1.0)\n",
            "    \n",
            "    def mutate_connections(self, mutation_rate: float = 0.05):\n",
            "        \"\"\"Mutate connection structure\"\"\"\n",
            "        if random.random() < mutation_rate:\n",
            "            # Add connection\n",
            "            input_nodes = [nid for nid, node in self.nodes.items() if node.node_type != NodeType.OUTPUT]\n",
            "            output_nodes = [nid for nid, node in self.nodes.items() if node.node_type != NodeType.INPUT]\n",
            "            \n",
            "            if input_nodes and output_nodes:\n",
            "                input_node = random.choice(input_nodes)\n",
            "                output_node = random.choice(output_nodes)\n",
            "                self.add_connection(input_node, output_node)\n",
            "    \n",
            "    def mutate_nodes(self, mutation_rate: float = 0.03):\n",
            "        \"\"\"Mutate node structure\"\"\"\n",
            "        if random.random() < mutation_rate:\n",
            "            # Add node by splitting connection\n",
            "            enabled_connections = [cid for cid, conn in self.connections.items() if conn.enabled]\n",
            "            if enabled_connections:\n",
            "                connection_id = random.choice(enabled_connections)\n",
            "                self.add_node(connection_id)\n",
            "    \n",
            "    def mutate(self, mutation_rate: float = 0.1):\n",
            "        \"\"\"Apply all mutations\"\"\"\n",
            "        self.mutate_weights(mutation_rate)\n",
            "        self.mutate_connections(mutation_rate * 0.5)\n",
            "        self.mutate_nodes(mutation_rate * 0.3)\n",
            "    \n",
            "    def copy(self):\n",
            "        \"\"\"Create a deep copy of the genome\"\"\"\n",
            "        new_genome = NEATGenome(self.input_size, self.output_size)\n",
            "        new_genome.nodes = {k: copy.deepcopy(v) for k, v in self.nodes.items()}\n",
            "        new_genome.connections = {k: copy.deepcopy(v) for k, v in self.connections.items()}\n",
            "        new_genome.fitness = self.fitness\n",
            "        new_genome.adjusted_fitness = self.adjusted_fitness\n",
            "        new_genome.species_id = self.species_id\n",
            "        return new_genome\n",
            "\n",
            "# NEAT Species Implementation\n",
            "class NEATSpecies:\n",
            "    \"\"\"Self-contained NEAT species implementation\"\"\"\n",
            "    \n",
            "    def __init__(self, species_id: int, representative: NEATGenome):\n",
            "        self.species_id = species_id\n",
            "        self.representative = representative\n",
            "        self.members = [representative]\n",
            "        self.fitness_history = []\n",
            "        self.stagnation = 0\n",
            "        self.best_fitness = 0.0\n",
            "    \n",
            "    def add_member(self, genome: NEATGenome):\n",
            "        \"\"\"Add a genome to this species\"\"\"\n",
            "        self.members.append(genome)\n",
            "        genome.species_id = self.species_id\n",
            "    \n",
            "    def remove_member(self, genome: NEATGenome):\n",
            "        \"\"\"Remove a genome from this species\"\"\"\n",
            "        if genome in self.members:\n",
            "            self.members.remove(genome)\n",
            "    \n",
            "    def get_fitness_stats(self):\n",
            "        \"\"\"Get fitness statistics for the species\"\"\"\n",
            "        if not self.members:\n",
            "            return 0.0, 0.0\n",
            "        \n",
            "        fitnesses = [m.fitness for m in self.members]\n",
            "        return max(fitnesses), np.mean(fitnesses)\n",
            "    \n",
            "    def update_stagnation(self):\n",
            "        \"\"\"Update stagnation counter\"\"\"\n",
            "        best_fitness, _ = self.get_fitness_stats()\n",
            "        \n",
            "        if best_fitness > self.best_fitness:\n",
            "            self.best_fitness = best_fitness\n",
            "            self.stagnation = 0\n",
            "        else:\n",
            "            self.stagnation += 1\n",
            "        \n",
            "        self.fitness_history.append(self.best_fitness)\n",
            "    \n",
            "    def select_parent(self) -> NEATGenome:\n",
            "        \"\"\"Select a parent genome using tournament selection\"\"\"\n",
            "        if not self.members:\n",
            "            return None\n",
            "        \n",
            "        # Tournament selection\n",
            "        tournament_size = min(3, len(self.members))\n",
            "        tournament = random.sample(self.members, tournament_size)\n",
            "        return max(tournament, key=lambda x: x.fitness)\n",
            "\n",
            "# NEAT Population Implementation\n",
            "class NEATPopulation:\n",
            "    \"\"\"Self-contained NEAT population implementation\"\"\"\n",
            "    \n",
            "    def __init__(self, input_size: int, output_size: int, population_size: int = 150):\n",
            "        self.input_size = input_size\n",
            "        self.output_size = output_size\n",
            "        self.population_size = population_size\n",
            "        self.population = []\n",
            "        self.species = []\n",
            "        self.generation = 0\n",
            "        self.innovation_number = 0\n",
            "        \n",
            "        # Initialize population with minimal genomes\n",
            "        for _ in range(population_size):\n",
            "            genome = NEATGenome(input_size, output_size)\n",
            "            self.population.append(genome)\n",
            "        \n",
            "        # Create initial species\n",
            "        self._speciate()\n",
            "    \n",
            "    def _speciate(self):\n",
            "        \"\"\"Organize genomes into species\"\"\"\n",
            "        # Clear existing species\n",
            "        for species in self.species:\n",
            "            species.members.clear()\n",
            "        \n",
            "        # Assign genomes to species\n",
            "        for genome in self.population:\n",
            "            assigned = False\n",
            "            \n",
            "            for species in self.species:\n",
            "                if self._genetic_distance(genome, species.representative) < 3.0:\n",
            "                    species.add_member(genome)\n",
            "                    assigned = True\n",
            "                    break\n",
            "            \n",
            "            if not assigned:\n",
            "                # Create new species\n",
            "                new_species = NEATSpecies(len(self.species), genome)\n",
            "                self.species.append(new_species)\n",
            "    \n",
            "    def _genetic_distance(self, genome1: NEATGenome, genome2: NEATGenome) -> float:\n",
            "        \"\"\"Calculate genetic distance between two genomes\"\"\"\n",
            "        # Simple distance metric (can be enhanced)\n",
            "        excess_genes = abs(len(genome1.connections) - len(genome2.connections))\n",
            "        disjoint_genes = 0\n",
            "        weight_diff = 0.0\n",
            "        \n",
            "        # Count matching genes\n",
            "        matching = 0\n",
            "        for conn1 in genome1.connections.values():\n",
            "            for conn2 in genome2.connections.values():\n",
            "                if conn1.input_node == conn2.input_node and conn1.output_node == conn2.output_node:\n",
            "                    matching += 1\n",
            "                    weight_diff += abs(conn1.weight - conn2.weight)\n",
            "                    break\n",
            "        \n",
            "        disjoint_genes = len(genome1.connections) + len(genome2.connections) - 2 * matching\n",
            "        \n",
            "        # Normalize by genome size\n",
            "        max_genes = max(len(genome1.connections), len(genome2.connections))\n",
            "        if max_genes == 0:\n",
            "            return 0.0\n",
            "        \n",
            "        return (excess_genes + disjoint_genes) / max_genes + weight_diff / max_genes\n",
            "    \n",
            "    def _crossover(self, parent1: NEATGenome, parent2: NEATGenome) -> NEATGenome:\n",
            "        \"\"\"Create offspring through crossover\"\"\"\n",
            "        # Ensure parent1 is more fit\n",
            "        if parent1.fitness < parent2.fitness:\n",
            "            parent1, parent2 = parent2, parent1\n",
            "        \n",
            "        # Create offspring\n",
            "        offspring = parent1.copy()\n",
            "        \n",
            "        # Inherit connections from both parents\n",
            "        for conn_id, conn1 in parent1.connections.items():\n",
            "            # Find matching connection in parent2\n",
            "            matching_conn = None\n",
            "            for conn2 in parent2.connections.values():\n",
            "                if conn1.input_node == conn2.input_node and conn1.output_node == conn2.output_node:\n",
            "                    matching_conn = conn2\n",
            "                    break\n",
            "            \n",
            "            if matching_conn:\n",
            "                # Inherit randomly from either parent\n",
            "                if random.random() < 0.5:\n",
            "                    offspring.connections[conn_id].weight = conn1.weight\n",
            "                    offspring.connections[conn_id].enabled = conn1.enabled\n",
            "                else:\n",
            "                    offspring.connections[conn_id].weight = matching_conn.weight\n",
            "                    offspring.connections[conn_id].enabled = matching_conn.enabled\n",
            "            # If no matching connection, keep parent1's connection\n",
            "        \n",
            "        return offspring\n",
            "    \n",
            "    def reproduce(self) -> 'NEATPopulation':\n",
            "        \"\"\"Create next generation\"\"\"\n",
            "        # Update species stagnation\n",
            "        for species in self.species:\n",
            "            species.update_stagnation()\n",
            "        \n",
            "        # Remove stagnant species\n",
            "        self.species = [s for s in self.species if s.stagnation < 15]\n",
            "        \n",
            "        # Calculate adjusted fitness for each species\n",
            "        for species in self.species:\n",
            "            for member in species.members:\n",
            "                member.adjusted_fitness = member.fitness / len(species.members)\n",
            "        \n",
            "        # Create new population\n",
            "        new_population = []\n",
            "        \n",
            "        # Elitism: keep best member from each species\n",
            "        for species in self.species:\n",
            "            if species.members:\n",
            "                best_member = max(species.members, key=lambda x: x.fitness)\n",
            "                new_population.append(best_member.copy())\n",
            "        \n",
        "        \n",
        "        # Fill remaining slots\n",
        "        while len(new_population) < self.population_size:\n",
        "            # Select species based on adjusted fitness\n",
        "            species_fitness = [sum(m.adjusted_fitness for m in s.members) for s in self.species]\n",
        "            total_fitness = sum(species_fitness)\n",
        "            \n",
        "            if total_fitness > 0:\n",
        "                # Roulette wheel selection\n",
        "                r = random.uniform(0, total_fitness)\n",
        "                cumsum = 0\n",
        "                selected_species = None\n",
        "                \n",
        "                for i, fitness in enumerate(species_fitness):\n",
        "                    cumsum += fitness\n",
        "                    if cumsum >= r:\n",
        "                        selected_species = self.species[i]\n",
        "                        break\n",
        "                \n",
        "                if selected_species and len(selected_species.members) > 1:\n",
        "                    # Crossover\n",
        "                    parent1 = selected_species.select_parent()\n",
        "                    parent2 = selected_species.select_parent()\n",
        "                    \n",
        "                    if parent1 and parent2 and parent1 != parent2:\n",
        "                        offspring = self._crossover(parent1, parent2)\n",
        "                    else:\n",
        "                        offspring = parent1.copy() if parent1 else selected_species.members[0].copy()\n",
        "                else:\n",
        "                    # Clone best member\n",
        "                    offspring = selected_species.members[0].copy() if selected_species.members else self.population[0].copy()\n",
        "                \n",
        "                # Mutate offspring\n",
        "                offspring.mutate()\n",
        "                new_population.append(offspring)\n",
        "            else:\n",
        "                # Fallback: random selection and mutation\n",
        "                parent = random.choice(self.population)\n",
        "                offspring = parent.copy()\n",
        "                offspring.mutate()\n",
        "                new_population.append(offspring)\n",
        "        \n",
        "        # Create new population object\n",
        "        new_pop = NEATPopulation(self.input_size, self.output_size, self.population_size)\n",
        "        new_pop.population = new_population\n",
        "        new_pop.generation = self.generation + 1\n",
        "        new_pop.innovation_number = self.innovation_number\n",
        "        \n",
        "        # Speciate new population\n",
        "        new_pop._speciate()\n",
        "        \n",
        "        return new_pop\n",
        "\n",
        "# NEAT Configuration\n",
        "class NEATConfig:\n",
        "    \"\"\"Self-contained NEAT configuration\"\"\"\n",
        "    \n",
        "    def __init__(self):\n",
        "        self.population_size = 150\n",
        "        self.fitness_threshold = 100.0\n",
        "        self.max_generations = 1000\n",
        "        self.mutation_rate = 0.1\n",
        "        self.weight_mutation_rate = 0.8\n",
        "        self.node_mutation_rate = 0.03\n",
        "        self.connection_mutation_rate = 0.05\n",
        "        self.species_threshold = 3.0\n",
        "        self.elitism = 2\n",
        "        self.stagnation_limit = 15\n",
        "\n",
        "# Test self-contained implementations\n",
        "print(\"✅ Self-contained NEAT implementations added:\")\n",
        "print(\"  - NEATNode: Complete node implementation\")\n",
        "print(\"  - NEATConnection: Complete connection implementation\")\n",
        "print(\"  - NEATGenome: Complete genome implementation\")\n",
        "print(\"  - NEATSpecies: Complete species implementation\")\n",
        "print(\"  - NEATPopulation: Complete population implementation\")\n",
        "print(\"  - NEATConfig: Complete configuration\")\n",
        "print(\"\\n🚀 All dependencies are now self-contained!\")\n",
        "print(\"   The notebook can run independently on Colab/Kaggle.\")"
        ]
    }
    
    # Insert the self-contained implementations cell after the imports
    notebook['cells'].insert(imports_cell_index + 1, self_contained_cell)
    
    # Now add fallback import handling to the NEAT imports cell
    neat_imports_cell_index = None
    for i, cell in enumerate(notebook['cells']):
        if "NEAT Imports" in ''.join(cell['source']):
            neat_imports_cell_index = i
            break
    
    if neat_imports_cell_index is not None:
        # Update the NEAT imports cell with fallback handling
        notebook['cells'][neat_imports_cell_index]['source'] = [
            "# NEAT Implementation Imports with Fallback\n",
            "try:\n",
            "    # Try to import from custom modules first\n",
            "    from neat_implementation.neat_core import NEATPopulation, NEATConfig, NEATGenome\n",
            "    from neat_implementation.neat_network import NodeType, ActivationFunction\n",
            "    print(\"✅ Successfully imported NEAT modules from custom implementation\")\n",
            "    \n",
            "except ImportError:\n",
            "    # Fallback to self-contained implementations\n",
            "    print(\"⚠️  Custom NEAT modules not found, using self-contained implementations\")\n",
            "    print(\"   This ensures the notebook runs on any platform (Colab, Kaggle, etc.)\")\n",
            "    \n",
            "    # The self-contained implementations are already available above\n",
            "    pass\n",
            "\n",
            "# EvoJAX compatibility interface\n",
            "try:\n",
            "    from neat_implementation.evojax_neat_interface import NEATEvoJAXInterface\n",
            "    print(\"✅ Successfully imported EvoJAX compatibility interface\")\n",
            "    \n",
            "except ImportError:\n",
            "    print(\"⚠️  EvoJAX compatibility interface not found\")\n",
            "    print(\"   Some advanced features may not be available\")\n",
            "    NEATEvoJAXInterface = None"
        ]
    
    # Save the updated notebook
    with open('complete_neat_training.ipynb', 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    
    print("✅ Dependency issues fixed with self-contained implementations and fallback mechanisms!")

if __name__ == "__main__":
    fix_dependency_issues()
